payload:
  - '+.microsoft.com'
  - '+.windowsupdate.com'
  - '+.windows.com'
  - '+.live.com'
  - '+.office.com'
  - '+.office365.com'
  - '+.sharepoint.com'
  - '+.onedrive.com'
  - '+.msftconnecttest.com'
  - '+.msftncsi.com'
  - '+.visualstudio.com'
  - '+.azure.com'
  - '+.azureedge.net'
